- name: Push generated webpage to another repository
  uses: nkoppel/push-files-to-another-repository@v1.1.3
  env:
    API_TOKEN_GITHUB: "${{ secrets.API_TOKEN_GITHUB }}"
  with:
    source-files: pages/
    destination-username: pysavantcodes
    destination-repository: https://github.com/pysavantcodes/Odic-Ai.git
    destination-directory: src/
    commit-email: uwakblessing1@gmail.com
